package lehena;
// Generated 12-ene-2020 13:29:37 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Alojamenduak generated by hbm2java
 */
public class Alojamenduak implements java.io.Serializable {

	private int idAlojamenduak;
	private String izena;
	private String deskribapena;
	private String udalerri;
	private String probintzia;
	private String email;
	private String telefonoa;
	private String web;
	private Set reservases = new HashSet(0);

	public Alojamenduak() {
	}

	public Alojamenduak(int idAlojamenduak) {
		this.idAlojamenduak = idAlojamenduak;
	}

	public Alojamenduak(int idAlojamenduak, String izena, String deskribapena, String udalerri, String probintzia,
			String email, String telefonoa, String web, Set reservases) {
		this.idAlojamenduak = idAlojamenduak;
		this.izena = izena;
		this.deskribapena = deskribapena;
		this.udalerri = udalerri;
		this.probintzia = probintzia;
		this.email = email;
		this.telefonoa = telefonoa;
		this.web = web;
		this.reservases = reservases;
	}

	public int getIdAlojamenduak() {
		return this.idAlojamenduak;
	}

	public void setIdAlojamenduak(int idAlojamenduak) {
		this.idAlojamenduak = idAlojamenduak;
	}

	public String getIzena() {
		return this.izena;
	}

	public void setIzena(String izena) {
		this.izena = izena;
	}

	public String getDeskribapena() {
		return this.deskribapena;
	}

	public void setDeskribapena(String deskribapena) {
		this.deskribapena = deskribapena;
	}

	public String getUdalerri() {
		return this.udalerri;
	}

	public void setUdalerri(String udalerri) {
		this.udalerri = udalerri;
	}

	public String getProbintzia() {
		return this.probintzia;
	}

	public void setProbintzia(String probintzia) {
		this.probintzia = probintzia;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelefonoa() {
		return this.telefonoa;
	}

	public void setTelefonoa(String telefonoa) {
		this.telefonoa = telefonoa;
	}

	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	public Set getReservases() {
		return this.reservases;
	}

	public void setReservases(Set reservases) {
		this.reservases = reservases;
	}

}
