package lehena;
// Generated 21-ene-2020 8:49:14 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Erabiltzaileak generated by hbm2java
 */
public class Erabiltzaileak implements java.io.Serializable {

	private Integer idBezeroak;
	private String izenAbizena;
	private String pasahitza;
	private String erabIzena;
	private Set erreserbaks = new HashSet(0);

	public Erabiltzaileak() {
	}

	public Erabiltzaileak(String izenAbizena, String pasahitza, String erabIzena, Set erreserbaks) {
		this.izenAbizena = izenAbizena;
		this.pasahitza = pasahitza;
		this.erabIzena = erabIzena;
		this.erreserbaks = erreserbaks;
	}

	public Integer getIdBezeroak() {
		return this.idBezeroak;
	}

	public void setIdBezeroak(Integer idBezeroak) {
		this.idBezeroak = idBezeroak;
	}

	public String getIzenAbizena() {
		return this.izenAbizena;
	}

	public void setIzenAbizena(String izenAbizena) {
		this.izenAbizena = izenAbizena;
	}

	public String getPasahitza() {
		return this.pasahitza;
	}

	public void setPasahitza(String pasahitza) {
		this.pasahitza = pasahitza;
	}

	public String getErabIzena() {
		return this.erabIzena;
	}

	public void setErabIzena(String erabIzena) {
		this.erabIzena = erabIzena;
	}

	public Set getErreserbaks() {
		return this.erreserbaks;
	}

	public void setErreserbaks(Set erreserbaks) {
		this.erreserbaks = erreserbaks;
	}

}
