package lehena;
// Generated 24-ene-2020 9:43:04 by Hibernate Tools 5.4.7.Final

/**
 * Erreserbak generated by hbm2java
 */
public class Erreserbak implements java.io.Serializable {

	private Integer idErreserba;
	private Erabiltzaileak erabiltzaileak;
	private Ostatuak ostatuak;
	private String sartuData;
	private String ateraData;

	public Erreserbak() {
	}

	public Erreserbak(Erabiltzaileak erabiltzaileak, Ostatuak ostatuak) {
		this.erabiltzaileak = erabiltzaileak;
		this.ostatuak = ostatuak;
	}

	public Erreserbak(Erabiltzaileak erabiltzaileak, Ostatuak ostatuak, String sartuData, String ateraData) {
		this.erabiltzaileak = erabiltzaileak;
		this.ostatuak = ostatuak;
		this.sartuData = sartuData;
		this.ateraData = ateraData;
	}

	public Integer getIdErreserba() {
		return this.idErreserba;
	}

	public void setIdErreserba(Integer idErreserba) {
		this.idErreserba = idErreserba;
	}

	public Erabiltzaileak getErabiltzaileak() {
		return this.erabiltzaileak;
	}

	public void setErabiltzaileak(Erabiltzaileak erabiltzaileak) {
		this.erabiltzaileak = erabiltzaileak;
	}

	public Ostatuak getOstatuak() {
		return this.ostatuak;
	}

	public void setOstatuak(Ostatuak ostatuak) {
		this.ostatuak = ostatuak;
	}

	public String getSartuData() {
		return this.sartuData;
	}

	public void setSartuData(String sartuData) {
		this.sartuData = sartuData;
	}

	public String getAteraData() {
		return this.ateraData;
	}

	public void setAteraData(String ateraData) {
		this.ateraData = ateraData;
	}

}
