package lehena;
// Generated 21-ene-2020 8:49:14 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * Erreserbak generated by hbm2java
 */
public class Erreserbak implements java.io.Serializable {

	private Integer idErreserba;
	private Erabiltzaileak erabiltzaileak;
	private Ostatuak ostatuak;
	private Date sartuData;
	private Date ateraData;

	public Erreserbak() {
	}

	public Erreserbak(Erabiltzaileak erabiltzaileak, Ostatuak ostatuak) {
		this.erabiltzaileak = erabiltzaileak;
		this.ostatuak = ostatuak;
	}

	public Erreserbak(Erabiltzaileak erabiltzaileak, Ostatuak ostatuak, Date sartuData, Date ateraData) {
		this.erabiltzaileak = erabiltzaileak;
		this.ostatuak = ostatuak;
		this.sartuData = sartuData;
		this.ateraData = ateraData;
	}

	public Integer getIdErreserba() {
		return this.idErreserba;
	}

	public void setIdErreserba(Integer idErreserba) {
		this.idErreserba = idErreserba;
	}

	public Erabiltzaileak getErabiltzaileak() {
		return this.erabiltzaileak;
	}

	public void setErabiltzaileak(Erabiltzaileak erabiltzaileak) {
		this.erabiltzaileak = erabiltzaileak;
	}

	public Ostatuak getOstatuak() {
		return this.ostatuak;
	}

	public void setOstatuak(Ostatuak ostatuak) {
		this.ostatuak = ostatuak;
	}

	public Date getSartuData() {
		return this.sartuData;
	}

	public void setSartuData(Date sartuData) {
		this.sartuData = sartuData;
	}

	public Date getAteraData() {
		return this.ateraData;
	}

	public void setAteraData(Date ateraData) {
		this.ateraData = ateraData;
	}

}
