package lehena;
// Generated 03-feb-2020 9:22:48 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ostatuak generated by hbm2java
 */
public class Ostatuak implements java.io.Serializable {

	private String sinadura;
	private String izena;
	private String deskribapena;
	private String udalerri;
	private String probintzia;
	private String email;
	private String telefonoa;
	private String web;
	private Double longitudea;
	private Double latitudea;
	private String ostatuMota;


	public Ostatuak() {
	}

	public Ostatuak(String sinadura) {
		this.sinadura = sinadura;
	}

	public Ostatuak(String sinadura, String izena, String deskribapena, String udalerri, String probintzia,
			String email, String telefonoa, String web, Double longitudea, Double latitudea, String ostatuMota) {
		this.sinadura = sinadura;
		this.izena = izena;
		this.deskribapena = deskribapena;
		this.udalerri = udalerri;
		this.probintzia = probintzia;
		this.email = email;
		this.telefonoa = telefonoa;
		this.web = web;
		this.longitudea = longitudea;
		this.latitudea = latitudea;
		this.ostatuMota = ostatuMota;
	}

	public String getSinadura() {
		return this.sinadura;
	}

	public void setSinadura(String sinadura) {
		this.sinadura = sinadura;
	}

	public String getIzena() {
		return this.izena;
	}

	public void setIzena(String izena) {
		this.izena = izena;
	}

	public String getDeskribapena() {
		return this.deskribapena;
	}

	public void setDeskribapena(String deskribapena) {
		this.deskribapena = deskribapena;
	}

	public String getUdalerri() {
		return this.udalerri;
	}

	public void setUdalerri(String udalerri) {
		this.udalerri = udalerri;
	}

	public String getProbintzia() {
		return this.probintzia;
	}

	public void setProbintzia(String probintzia) {
		this.probintzia = probintzia;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelefonoa() {
		return this.telefonoa;
	}

	public void setTelefonoa(String telefonoa) {
		this.telefonoa = telefonoa;
	}

	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	public Double getLongitudea() {
		return this.longitudea;
	}

	public void setLongitudea(Double longitudea) {
		this.longitudea = longitudea;
	}

	public Double getLatitudea() {
		return this.latitudea;
	}

	public void setLatitudea(Double latitudea) {
		this.latitudea = latitudea;
	}

	public String getOstatuMota() {
		return this.ostatuMota;
	}

	public void setOstatuMota(String ostatuMota) {
		this.ostatuMota = ostatuMota;
	}

}
