package lehena;
// Generated 12-ene-2020 13:29:37 by Hibernate Tools 5.4.7.Final

/**
 * Reservas generated by hbm2java
 */
public class Reservas implements java.io.Serializable {

	private int idReservas;
	private Alojamenduak alojamenduak;
	private Erabiltzaileak erabiltzaileak;
	private String reservascol;

	public Reservas() {
	}

	public Reservas(int idReservas, Alojamenduak alojamenduak, Erabiltzaileak erabiltzaileak) {
		this.idReservas = idReservas;
		this.alojamenduak = alojamenduak;
		this.erabiltzaileak = erabiltzaileak;
	}

	public Reservas(int idReservas, Alojamenduak alojamenduak, Erabiltzaileak erabiltzaileak, String reservascol) {
		this.idReservas = idReservas;
		this.alojamenduak = alojamenduak;
		this.erabiltzaileak = erabiltzaileak;
		this.reservascol = reservascol;
	}

	public int getIdReservas() {
		return this.idReservas;
	}

	public void setIdReservas(int idReservas) {
		this.idReservas = idReservas;
	}

	public Alojamenduak getAlojamenduak() {
		return this.alojamenduak;
	}

	public void setAlojamenduak(Alojamenduak alojamenduak) {
		this.alojamenduak = alojamenduak;
	}

	public Erabiltzaileak getErabiltzaileak() {
		return this.erabiltzaileak;
	}

	public void setErabiltzaileak(Erabiltzaileak erabiltzaileak) {
		this.erabiltzaileak = erabiltzaileak;
	}

	public String getReservascol() {
		return this.reservascol;
	}

	public void setReservascol(String reservascol) {
		this.reservascol = reservascol;
	}

}
